version: '3.5'
services:
  tgf:
    image: modaniru/tgf:latest
    environment:
      - TWITCH_CLIENT_ID=id
      - TWITCH_CLIENT_SECRET=secret
    restart: unless-stopped
  image-service:
    image: modaniru/tgf-image-generator:latest
    restart: unless-stopped
    environment:
      TGF_SERVICE_HOST: tgf:8080
    depends_on:
      - tgf
  grpc-gateway:
    image: modaniru/tgf-grpc-gate-way:latest
    restart: unless-stopped
    environment:
      TGF_HOST: tgf:8080
      IMAGE_HOST: image-service:8080
    ports:
      - "80:8080"
    depends_on:
      - tgf
      - image-service
